### ISSUE TITLE
Login Netatmo

### ISSUE THREAD

**Issue by Toby-Huncke** [demel42/IPSymconNetatmoAircare#1]
Hallo,
ich habe seit Mitte Juli folgendes Problem. Wenn ich mich in der IO Instanz bei Netatmo im Browser Fenster anmelden möchte passiert nicht. Im Debug steht "UpdateData | Instance is inactive (not logged in) => pause". Mir ist jedoch aufgefallen, dass er im Login versucht sich mit einer anderen email Andresse von mir anzumelden (Login | url=https://oauth.ipmagic.de/authorize/netatmo?username=**xxxxx.xxxx%40web.de**). Diese kann ich aber nirgends ändern. Mir nicht sicher was ich im Juli geändert habe. Kann mich jedoch erinnern, dass ich in diesem Zeitraum auf DSM7 der Synology umgestellt habe.

**Comment by demel42** [comment]
Die Anmeldung via OAuth (also Symcon-connect) funktioniert nicht mehr. Netatmo sagt, bei denen ist alles in Ordnung und paresy hat es nicht hinbekommen, das zu klären.
Daher gibt es nur die Möglichkeit, per Entwicklerschlüssel (gilt für alle Netatmo-Produkte), aber auch da hatte Netatmo etwas geändert, sodaß man zu einem Trick greifen muss.
siehe https://community.symcon.de/t/modul-netatmo-camera-presence-welcome/45971/184?u=demel42
Was das Passwort angeht kann ich eher nichts dazu sagen - ich habe im Code nichts, das ein anderes Login vorspielt und der OAuth-teil liegt bei paresy.
Was ich bei der o.g. URL übergebe ist die Mail-Adresse, mit dem Du die Lizenz bei Symcon registriert hattest - hat nicht s zu tun mit dem Username bei Netatmo. OAUth funktioniert ja so, das du dann eine Login-Seite von dem jew. Hersteller (also in dem Fall Netamo) präsentiert bekommst und dich dort mit den Daten anmeldest, die für das Fremdsystem relevant sind.

**Comment by Toby-Huncke** [comment]
Vielen Dank Demel,
ich hatte lange gesucht aber den Beitrag hatte ich leider nicht gefunden.,

**Comment by demel42** [comment]
kein Problem, das ist mit den 3 getrennten Modulen für Netatmo auch etwas unübersichtlich.
Mit heutigem Wissen (um Netatmo und um IPS) hätte ich das in ein Modul zusammengefasst.
Naja, Schnee von gestern
